version: '3'
services: 
    frontend:
        image: akap/frontend:1.0
        stdin_open: true
        depends_on:
            - backend
        ports: 
            - "3000:3000"
        networks: 
            - akap-app
        depends_on: 
            - api-server
    api-server:
        image: akap/backend:1.0
        ports: 
            - "1337:1337"
        networks: 
            - akap-app

networks: 
    akap-app:
        driver: bridge
